# monetary-unit: Set what monetary unit you want to use
monetary-unit: ì›

# default-money: Set default money when player joined the server first
default-money: 1000

# max-money: Set max money that player can have
max-money: 9999999999

# Whether to allow player to pay when taret player is offline
allow-pay-offline: true

# auto-save-interval: Set interval of auto-save
auto-save-interval: 10

# provider: Set provider of database (Available: yaml)
provider: yaml
